# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
sudo: false
dist: trusty

language: scala

install: true

script: mvn --batch-mode --no-snapshot-updates install && cd blog-tutorial-shared && sbt package
